<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Theiconnz\Campaigns\Block\Page\Campaign */
?>

<form class="form contact"
      id="campaign_form"
      method="post"
      enctype="multipart/form-data"
      data-mage-init='{"Theiconnz_Campaigns/js/campaigns":
              {
                "validationURL" : "<?= $block->escapeUrl($block->getFormAction()) ?>",
                "fileuploadid": "#file-upload",
                "formelement": "#campaign_form",
                "successblock": "#campaign-data-form-update",
                "formcontainer": ".campaign-data-form",
                "formid": "campaign_form"
              }
          }'
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'
    >
    <?= $block->getBlockHtml('formkey') ?>
    <input type="hidden" name="cid" value="<?= $block->getCampaignId()?>" />

    <div id="campaign-data-form" class="campaign-data-form campaign-data-form-container">
        <fieldset class="fieldset">
            <?php if( $this->getPage()->getShowname() ){?>
            <div class="field name required">
                <div class="control">
                    <input name="firstname"
                           id="firstname"
                           title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                           value=""
                           class="input-text"
                           type="text"
                           placeholder="<?= $block->escapeHtml(__('Name*')) ?>"
                           data-validate="{required:true, minlength:2}"/>
                </div>
            </div>
            <?php } ?>
            <?php
            if( $this->getPage()->getShowLastname() ){?>
                <div class="field name required">
                    <div class="control">
                        <input name="lastname"
                               id="lastname"
                               title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>"
                               value=""
                               class="input-text"
                               type="text"
                               placeholder="<?= $block->escapeHtml(__('Last Name*')) ?>"
                               data-validate="{required:false, minlength:1}"/>
                    </div>
                </div>
            <?php } ?>
            <?php if( $this->getPage()->getShowemail() ){?>
            <div class="field email required">
                <div class="control">
                    <input name="email"
                           id="email"
                           title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           value=""
                           class="input-text"
                           type="email"
                           placeholder="<?= $block->escapeHtml(__('Email*')) ?>"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <?php } ?>
            <?php if( $this->getPage()->getShowphone() ){?>
            <div class="field telephone">
                <div class="control">
                    <input name="telephone"
                           id="telephone"
                           title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                           value=""
                           placeholder="<?= $block->escapeHtml(__('Phone Number*')) ?>"
                           class="input-text"
                           type="tel" />
                </div>
            </div>
            <?php } ?>
            <?php if( $this->getPage()->getShowcontent() ){?>
            <div class="field content required">
                <div class="control">
                    <textarea name="content"
                              id="comment"
                              title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                              class="input-text"
                              cols="5"
                              rows="3"
                              placeholder="<?= $block->escapeHtml(__('Tell us your story here, in 25 words or less...')) ?>"
                              data-validate="{maxlength:1000}"
                    ></textarea>
                </div>
            </div>
            <?php } ?>
            <?php if( $this->getPage()->getShowupload() ){?>
            <div class="field fileupload">
                <div class="control">
                    <div class="upload-ins">
                        <input type="file"
                               name="filename"
                               class="inputfile"
                               id="file-upload"
                               placeholder="<?= $block->escapeHtml(__('Upload supporting image')) ?>"
                               accept="image/jpeg,image/png"
                               data-mage-init='{"Theiconnz_Campaigns/js/upload":
                                  {
                                    "fileuploadcontent": "upload-content-data"
                                  }
                              }'
                        />
                        <div class="inst" id="upload-content-data">Upload Supporting Image</div>
                        <div class="icons"><i class="export-icon"></i></div>
                    </div>
                </div>
            </div>
            <?php } ?>
        </fieldset>
    </div>

    <div class="campaign-data-form campaign-data-form-container checkbox-container">
        <fieldset class="fieldset">
            <div class="field terms field-checkbox">
                <label class="label" for="terms-error">
                    <span><?= $block->escapeHtml(__('I have read and agreed to the Terms & Conditions*')) ?></span>
                </label>
                <div class="control">
                    <input type="checkbox"
                           name="terms"
                           class="input-text"
                           value="1"
                           data-validate="{required:true}"
                           aria-describedby="terms-error"
                    />
                </div>
            </div>

            <?php if( $this->getPage()->getShowupload() ){?>
            <div class="field use_marketing field-checkbox">
                <label class="label" for="useinmarketing-error">
                    <span><?= $block->escapeHtml(__('I agree to my  and image used for marketing purposes')) ?></span>
                </label>
                <div class="control">
                    <input type="checkbox"
                           name="useinmarketing"
                           class="input-text"
                           value="1"
                           aria-describedby="useinmarketing-error"
                    />
                </div>
            </div>
            <?php } ?>
            <?php if( $this->getPage()->getNewsletter() ){?>
            <div class="field newsletter field-checkbox">
                <label class="label" for="newsletter-error">
                    <span><?= $block->escapeHtml(__('Sign me up for emails about promotions & discounts')) ?></span>
                </label>
                <div class="control">
                    <input type="checkbox"
                           name="newsletter"
                           class="input-text"
                           value="1"
                           aria-describedby="useinmarketing-error"
                    />
                </div>
            </div>
            <?php } ?>

            <?= $block->getChildHtml('form.additional.info') ?>
        </fieldset>


        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('ENTER')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('ENTER')) ?></span>
                </button>
            </div>
            <span class="mandatory-text">
            *Mandatory fields.
            </span>
        </div>
    </div>

    <div id="campaign-data-form-update" class="campaign-data-form-container" style="display: none;">
        <?php
        $blockid = $block->getPage()->getData('block_identifier');
        if($blockid) {
            echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId($blockid)
                ->toHtml();
        }
        ?>
    </div>
</form>


<script type="text/javascript">
    require(['jquery', 'jquery/ui', 'accordion'], function($){
        $(document).ready( function() {
            $("#campaign-view-accordiaon").accordion();

            $("#accordion").accordion();
        });
    });
</script>

